### ISSUE TITLE
handshake failure

### ISSUE THREAD

**Issue by reaperleo** [anyproto/any-sync-dockercompose#89] opened 2024-08-08 06:31 UTC
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [X] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

Hi Team,

I updated the self hosted anytype to the latest version and I am getting the below error.

any-sync-filenode-1  | 2024-08-08T06:19:15.255Z WARN    net.transport.yamux     incoming connection handshake error     {"error": "IncompatibleVersion"}
any-sync-filenode-1  | 2024-08-08T06:19:15.370Z INFO    net.transport.quic      accept error    {"localAddr": "172.21.0.12:1015", "error": "IncompatibleVersion"}
any-sync-filenode-1  | 2024-08-08T06:19:15.382Z WARN    net.transport.yamux     incoming connection handshake error     {"error": "IncompatibleVersion"}
any-sync-filenode-1  | 2024-08-08T06:19:15.400Z INFO    net.transport.quic      accept error    {"localAddr": "172.21.0.12:1015", "error": "IncompatibleVersion"}
any-sync-filenode-1  | 2024-08-08T06:19:15.412Z WARN    net.transport.yamux     incoming connection handshake error     {"error": "IncompatibleVersion"}
any-sync-filenode-1  | 2024-08-08T06:19:15.499Z INFO    net.transport.quic      accept error    {"localAddr": "172.21.0.12:1015", "error": "Application error 0x3 (remote): outbound handshake failed"}

could you please assist 

### Expected Behavior

expecting the files to sync between devices but I am getting an error 

### Steps To Reproduce

I followed the procedure as mentioned in the doc

### Environment

```markdown
- OS: Linux
```

**Comment by fb929** [comment] 2024-08-08 14:13
Have you updated your client to the latest version?

**Comment by Talanor** [comment] 2024-08-08 14:29
Possible duplicate of #87 ? Same error messages.

**Comment by reaperleo** [comment] 2024-08-08 23:59
> Have you updated your client to the latest version?

Yes I have install the latest version

**Comment by reaperleo** [comment] 2024-08-09 00:21
> Possible duplicate of #87 ? Same error messages.

it might be I just upgraded the docker images and I got this error. I use the same client.yml

**Comment by fb929** [comment] 2024-08-09 16:07
I can't reproduce this bug guys...
can you show me the client and server versions please?
to get the client version, use "about".
to get the server versions please show me output for command: ```docker ps```

**Comment by reaperleo** [comment] 2024-08-10 02:01
I updated the server  from version 4 to 5.0.2  and for client I use the 0.42.3-1 version

```
CONTAINER ID   IMAGE                                            COMMAND                  CREATED        STATUS                  PORTS                                                                                                                                                                                 NAMES
309c13b66f6f   ghcr.io/anyproto/any-sync-filenode:latest        "/bin/any-sync-filen…"   44 hours ago   Up 28 hours             443/tcp, 8080/tcp, 0.0.0.0:1005->1005/tcp, :::1005->1005/tcp, 0.0.0.0:1015->1015/udp, :::1015->1015/udp, 0.0.0.0:8004->8000/tcp, :::8004->8000/tcp                                    any-sync-dockercompose-any-sync-filenode-1
734fae5a611c   ghcr.io/anyproto/any-sync-node:latest            "/bin/any-sync-node …"   44 hours ago   Up 28 hours             443/tcp, 0.0.0.0:1002->1002/tcp, :::1002->1002/tcp, 0.0.0.0:1012->1012/udp, :::1012->1012/udp, 0.0.0.0:8002->8000/tcp, :::8002->8000/tcp, 0.0.0.0:8082->8080/tcp, :::8082->8080/tcp   any-sync-dockercompose-any-sync-node-2-1
87ad9492e812   ghcr.io/anyproto/any-sync-consensusnode:latest   "/bin/any-sync-conse…"   44 hours ago   Up 29 seconds           443/tcp, 8080/tcp, 0.0.0.0:1006->1006/tcp, :::1006->1006/tcp, 0.0.0.0:1016->1016/udp, :::1016->1016/udp, 0.0.0.0:8006->8000/tcp, :::8006->8000/tcp                                    any-sync-dockercompose-any-sync-consensusnode-1
a7933aaf2d75   ghcr.io/anyproto/any-sync-node:latest            "/bin/any-sync-node …"   44 hours ago   Up 28 hours             443/tcp, 0.0.0.0:1003->1003/tcp, :::1003->1003/tcp, 0.0.0.0:1013->1013/udp, :::1013->1013/udp, 0.0.0.0:8003->8000/tcp, :::8003->8000/tcp, 0.0.0.0:8083->8080/tcp, :::8083->8080/tcp   any-sync-dockercompose-any-sync-node-3-1
2a9e127e983b   ghcr.io/anyproto/any-sync-node:latest            "/bin/any-sync-node …"   44 hours ago   Up 28 hours             443/tcp, 0.0.0.0:1001->1001/tcp, :::1001->1001/tcp, 0.0.0.0:1011->1011/udp, :::1011->1011/udp, 0.0.0.0:8001->8000/tcp, :::8001->8000/tcp, 0.0.0.0:8081->8080/tcp, :::8081->8080/tcp   any-sync-dockercompose-any-sync-node-1-1
8ba2617dd4a5   ghcr.io/anyproto/any-sync-coordinator:latest     "/bin/any-sync-coord…"   44 hours ago   Up 28 hours             443/tcp, 8080/tcp, 0.0.0.0:1004->1004/tcp, :::1004->1004/tcp, 0.0.0.0:1014->1014/udp, :::1014->1014/udp, 0.0.0.0:8005->8000/tcp, :::8005->8000/tcp                                    any-sync-dockercompose-any-sync-coordinator-1
18c431fee5ec   redis/redis-stack-server:7.2.0-v6                "redis-server --port…"   44 hours ago   Up 28 hours (healthy)   0.0.0.0:6379->6379/tcp, :::6379->6379/tcp                                                                                                                                             any-sync-dockercompose-redis-1
3956566b5044   minio/minio:RELEASE.2024-07-04T14-25-45Z         "/usr/bin/docker-ent…"   44 hours ago   Up 28 hours (healthy)   0.0.0.0:9000-9001->9000-9001/tcp, :::9000-9001->9000-9001/tcp                                                                                                                         any-sync-dockercompose-minio-1
```

**Comment by fb929** [comment] 2024-08-10 14:23
you are using the "latest" version for any-sync-* daemons, which caused the error.
was this a conscious choice, or did something go wrong?

**Comment by reaperleo** [comment] 2024-08-10 23:32
> you are using the "latest" version for any-sync-* daemons, which caused the error.
> was this a conscious choice, or did something go wrong?

I updated the server to the latest version by choice. I think nothing went wrong (no errors). If I downgrade the server, will the issue be resolved?

**Comment by fb929** [comment] 2024-08-11 17:25
the latest builds include "nightly builds" and all test builds.
in this specific case, you most likely got a test build with a new protocol version.
I recommend using [prod](https://github.com/anyproto/any-sync-dockercompose/blob/main/.env.override.prod) versions.

**Comment by fb929** [comment] 2024-08-11 17:26
@Talanor do you have the same case?

**Comment by reaperleo** [comment] 2024-08-12 00:10
> the latest builds include "nightly builds" and all test builds. in this specific case, you most likely got a test build with a new protocol version. I recommend using [prod](https://github.com/anyproto/any-sync-dockercompose/blob/main/.env.override.prod) versions.

I changed it to prod and it stoped syncing :(. Also I created a new server and a new key wasn't generated for the new vault

**Comment by fb929** [comment] 2024-08-12 17:12
> > the latest builds include "nightly builds" and all test builds. in this specific case, you most likely got a test build with a new protocol version. I recommend using [prod](https://github.com/anyproto/any-sync-dockercompose/blob/main/.env.override.prod) versions.
> 
> I changed it to prod and it stopped syncing :(. Also I created a new server and a new key wasn't generated for the new key vault. I linked the .env.override.prod to .env.override

If you have completely overwritten the `.env.override` file, you have likely removed the `EXTERNAL_LISTEN_HOSTS` parameter, and now the clients do not know the server address (assuming you do not have only local clients).

**Comment by reaperleo** [comment] 2024-08-12 23:19
> > > the latest builds include "nightly builds" and all test builds. in this specific case, you most likely got a test build with a new protocol version. I recommend using [prod](https://github.com/anyproto/any-sync-dockercompose/blob/main/.env.override.prod) versions.
> > 
> > 
> > I changed it to prod and it stopped syncing :(. Also I created a new server and a new key wasn't generated for the new key vault. I linked the .env.override.prod to .env.override
> 
> If you have completely overwritten the `.env.override` file, you have likely removed the `EXTERNAL_LISTEN_HOSTS` parameter, and now the clients do not know the server address (assuming you do not have only local clients).

thank you it worked :) to generate the key. but the sync error still exist :(

**Comment by reaperleo** [comment] 2024-08-14 01:39
I downgrade the any-sync-dockercompose  to 4.1.0 version and everything is working

**Comment by sususu98** [comment] 2024-08-14 07:59
You can check your config's `client.yml` file, Ensure that the `addresses` are correctly configured.
In the latest version you need to set `. env.override ` like this 
```yaml 
EXTERNAL_LISTEN_HOST=    #is null   
EXTERNAL_LISTEN_HOSTS=x.x.x.x
```

**Comment by fb929** [comment] 2024-08-14 15:36
> You can check your config's `client.yml` file, Ensure that the `addresses` are correctly configured. In the latest version you need to set `. env.override ` like this
> 
> ```yaml
> EXTERNAL_LISTEN_HOST=    #is null   
> EXTERNAL_LISTEN_HOSTS=x.x.x.x
> ```

Yes, it's a bug. I fixed it [here](https://github.com/anyproto/any-sync-dockercompose/pull/90).

**Comment by reaperleo** [comment] 2024-08-15 03:29
> > I downgrade the any-sync-dockercompose to 4.1.0 version and everything is working
> 
> Please try version [5.0.3](https://github.com/anyproto/any-sync-dockercompose/releases/tag/v5.0.3) - everything should work in it.

Thank you very much! I just tested it. after the update it works perfect with the new version

**Closed** 2024-08-15 15:05 UTC
Labels: bug
